version: "2"
services:
  cli:
    build: ./cli
    image: storj-cli
  db:
    image: mongo:3.4.0
    volumes:
      - ./mongodb/data:/data/db
  mq:
    image: rabbitmq:3.6.6
  bridge:
    build: ./bridge
    volumes:
      - ./bridge/bridge.config.json:/root/config.json
    command: ["./bin/storj-bridge.js", "-c", "/root/config.json"]
    environment:
      - DOCKER_SERVICES=db:27017
    ports:
      - 8080:8080
  landlord:
    build: ./complex
    volumes:
      - ./complex/landlord.config.json:/root/config.template.json
    command: ["./bin/storj-complex.js", "-c", "/root/config.json"]
    environment:
      - DOCKER_SERVICES=bridge:8080,db:27017,mq:5672
  renter:
    build: ./complex
    volumes:
      - ./complex/renter.config.json:/root/config.template.json
      - ./complex/hd-private.key:/root/hd-private.key
    command: ["./bin/storj-complex.js", "-c", "/root/config.json"]
    environment:
      - DOCKER_SERVICES=bridge:8080,db:27017,mq:5672
    restart: always
  farmer:
    build: ./farmer
    volumes:
      - ./farmer/data:/root/.storjshare
      - ./farmer/farmer.config.json:/root/.storjshare/config.template.json
    environment:
      - DOCKER_SERVICES=renter:4000
    command: ["./bin/storjshare.js", "start", "-p", "password"]
